// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("TDDBox")>]
[<assembly: AssemblyProductAttribute("TDDBox")>]
[<assembly: AssemblyDescriptionAttribute("TDD Box")>]
[<assembly: AssemblyVersionAttribute("1.0.1")>]
[<assembly: AssemblyFileVersionAttribute("1.0.1")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "TDDBox"
    let [<Literal>] AssemblyProduct = "TDDBox"
    let [<Literal>] AssemblyDescription = "TDD Box"
    let [<Literal>] AssemblyVersion = "1.0.1"
    let [<Literal>] AssemblyFileVersion = "1.0.1"
    let [<Literal>] AssemblyConfiguration = "Release"
